import { Bree_Serif, Nunito } from "next/font/google";
import "./globals.css";
import { Providers } from "../components/Providers";

const breeSerif = Bree_Serif({
  variable: "--font-bree-serif",
  subsets: ["latin"],
  weight: "400",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${breeSerif.variable} ${nunito.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
